---
- name: Install git
  become: yes
  apt:
    name: git
    state: present

- name: Check out a clone of bash-it repo
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: "{{ ansible_env.HOME }}/.bash-it"
    version: 260e1851efb3ca77884678edde17f1e15d67b5b0

- name: Already installed bash-it
  stat:
    path: "{{ ansible_env.HOME }}/.bashrc.bak"
  register: bashrc_bak

- name: Run the script for install
  command: "{{ ansible_env.HOME }}/.bash-it/install.sh"
  when: not bashrc_bak.stat.exists

- name: Modify the `.bashrc` for theme
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: present
    regexp: BASH_IT_THEME='.*'
    line: BASH_IT_THEME='clean'
