- hosts: local
  connection: local
  become: no
  roles:
    - {role: 'initialize', tags: 'initialize'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'docker-compose', tags: 'docker-compose'}


