- hosts: remote
  become: no
  roles:
    - {role: 'initialize', tags: 'initialize'}
    - {role: 'routing', tags: 'routing'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'docker-compose', tags: 'docker-compose'}
    - {role: 'bash-it', tags: 'bash-it'}
    - {role: 'vim', tags: 'vim'}
    - {role: 'anyenv', tags: 'anyenv'}

- hosts: vagrant
  become: no
  roles:
    - {role: 'initialize', tags: 'initialize'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'docker-compose', tags: 'docker-compose'}
    - {role: 'bash-it', tags: 'bash-it'}
    - {role: 'vim', tags: 'vim'}
    - {role: 'anyenv', tags: 'anyenv'}
# for high performance computer
#    - {role: 'gnome', tags: 'gnome'}
