- hosts: all
  become: no
  vars_files:
    - vars.yml
  roles:
    - {role: 'initialize', tags: 'initialize'}
    - {role: 'routing', tags: 'routing'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'docker-compose', tags: 'docker-compose'}
    - {role: 'bash-it', tags: 'bash-it'}
    - {role: 'vim', tags: 'vim'}
    - {role: 'anyenv', tags: 'anyenv'}
