
- name: Run this command to download the latest version of Docker Compose
  become: yes
  shell:
    curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Apply executable permissions to the binary
  become: yes
  shell:
    chmod +x /usr/local/bin/docker-compose
