
- name: Downloading the latest version of Docker Compose
  become: yes
  shell:
    curl -L "https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Apply executable permissions to the binary
  become: yes
  shell:
    chmod +x /usr/local/bin/docker-compose
