- name: Uninstall old versions
  become: yes
  apt:
    name: sublime-text
    state: absent

- name: Add Sublime's official GPG key
  become: yes
  shell:
    curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

- name: Add stable repository
  become: yes
  shell:
    echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

- name: Install the latest version of Sublime text
  become: yes
  apt:
    name: sublime-text
    state: latest